name: exam_to_pdf
description: A Flutter app that scans exam papers, translates, and generates typed PDFs.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_translation: ^0.7.0
  pdf: ^3.10.7
  path_provider: ^2.0.14
  file_picker: ^8.0.0
  open_filex: ^4.3.4
  flutter_font_picker: ^1.4.0
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
